server:
  port: 3000

spring:
  datasource:                                     # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource      # 数据源的类型，可以更改为其他的数据源配置，比如druid
    driver-class-name: com.mysql.cj.jdbc.Driver   # mysql/MariaDB 的数据库驱动类名称
    url: jdbc:mysql://localhost:3306/douyin?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: "010110"
    hikari:
      connection-timeout: 30000               # 等待连接池分配连接的最大时间（毫秒），超过这个时长还没有可用的连接，则会抛出SQLException
      minimum-idle: 5                         # 最小连接数
      maximum-pool-size: 20                   # 最大连接数
      auto-commit: true                       # 自动提交
      idle-timeout: 600000                    # 连接超时的最大时长（毫秒），超时则会被释放（retired）
      pool-name: DataSourceHikariCP           # 连接池的名字
      max-lifetime: 18000000                  # 连接池的最大生命时长（毫秒），超时则会被释放（retired）
      connection-test-query: SELECT 1

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0

  data:
    mongodb:
      uri: mongodb://root:010110@39.105.208.107:27017
      database: douyin

  rabbitmq:
    host: 39.105.208.107
    port: 5672
    username: admin
    password: admin
    virtual-host: douyin

#  application:
#    name: douyin
  cloud:
    nacos:
      discovery:
        server-addr: 39.105.208.107:8848  #nacos 地址

# 打开监控
management:
  endpoints:
    web:
      exposure:
        include: '*'

# MinIO 配置
minio:
  endpoint: http://39.105.208.107:9000      # MinIO服务地址
  fileHost: http://39.105.208.107:9000      # 文件地址host
  bucketName: douyin                      # 存储桶bucket名称
  accessKey: zyxlwl                         # 用户名
  secretKey: zyxlwl12345                     # 密码
  imgSize: 1024                           # 图片大小限制，单位：m
  fileSize: 1024                          # 文件大小限制，单位：m
